workflow updates

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -1,4 +1,4 @@
-name: Terraform Deployment
+name: Terraform and Ansible Deployment
 
 on:
   push:
@@ -26,10 +26,10 @@ jobs:
         run: |
           set -e
           terraform apply -auto-approve || {
-          echo "Terraform apply failed. Running destroy..."
-          terraform destroy -auto-approve
-          exit 1
-          } 
+            echo "Terraform apply failed. Running destroy..."
+            terraform destroy -auto-approve
+            exit 1
+          }
         working-directory: ./terraform
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -40,14 +40,14 @@ jobs:
           public_ip=$(terraform output -raw public_ip)
           echo "[web]" > ansible/inventory
           echo "$public_ip ansible_user=ubuntu" >> ansible/inventory
-        
+
       - name: Upload Terraform State
         uses: actions/upload-artifact@v3
         with:
           name: terraform-state
           path: terraform
 
-  cleanup:
+  destroy:
     runs-on: ubuntu-latest
     needs: terraform
     if: ${{ failure() }}
@@ -56,7 +56,7 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: terraform-state
-          
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
 
@@ -66,13 +66,36 @@ jobs:
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
       - name: Fix File Permissions
         run: |
           chmod +x .terraform/providers/registry.terraform.io/hashicorp/aws/4.67.0/linux_amd64/terraform-provider-aws_v4.67.0_x5
+
       - name: Terraform Destroy
-        run: |
-          terraform destroy -auto-approve
+        run: terraform destroy -auto-approve
         working-directory: ./
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+  ansible:
+    runs-on: ubuntu-latest
+    needs: [terraform, cleanup]
+    if: ${{ needs.terraform.result == 'success' && needs.cleanup.result == 'success' }}
+    steps:
+      - name: Download Terraform State
+        uses: actions/download-artifact@v3
+        with:
+          name: terraform-state
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install Ansible
+        run: sudo apt-get install -y ansible
+
+      - name: Run Ansible Playbook
+        run: ansible-playbook -i ansible/inventory ansible/playbook.yml
+        env:
+          ANSIBLE_HOST_KEY_CHECKING: 'False'
+          ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.SSH_PRIVATE_KEY }}
